version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=task_manager
      - POSTGRES_PASSWORD=task_manager
      - POSTGRES_DB=task_manager
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    networks:
      - task-manager-network

  task-manager:
    depends_on:
      - db
    image: ingostrah/task-manager:v0.0.1
    restart: always
    environment:
      - DB_PORT=5432
      - DB_HOST=172.20.0.2
    ports:
      - "8080:8080"
    networks:
      - task-manager-network

volumes:
  postgresql-data:

networks:
  task-manager-network:
    driver: bridge
